sudo: false
dist: trusty
language: python

addons:
  apt:
    update: true
    packages:
    - ffmpeg
    sources:
    - sourceline: 'ppa:mc3man/trusty-media'

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

before_install:
- pip install -U pip wheel setuptools

install:
- pip install .

before_script:
- ffmpeg -version
# test audio conversion
- curl -SsL "https://www.sample-videos.com/audio/mp3/wave.mp3" > test.mp3
- ffmpeg -v error -i test.mp3 -acodec copy -f mp3 - > /dev/null
# test video conversion
- curl -SsL "http://techslides.com/demos/sample-videos/small.mp4" > test.mp4
- ffmpeg -v error -i test.mp4 -vcodec copy -f matroska - > /dev/null

script:
- ffpb -i test.mp3 -acodec copy test.mka
- ffpb -i test.mp4 -vcodec copy test.mkv

before_deploy:
  - pip install -U twine
  - python setup.py sdist bdist_wheel

deploy:
  provider: script
  script: twine upload --skip-existing dist/*
  skip_cleanup: true
  on:
    tags: true
    repo: althonos/ffpb

notifications:
  email:
  - althonosdev@gmail.com
